## 1.Basic Initialization

In [35]:
import numpy as np

In [36]:
A = np.arange(1, 101)
A

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [37]:
B = np.zeros((3, 4))
B

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
C = np.ones((4,5), dtype=np.int32)
C

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [39]:
R = np.arange(1, 21, 3)
R

array([ 1,  4,  7, 10, 13, 16, 19])

In [40]:
arr_eye = np.eye(3)
arr_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
two_dim = np.array([(2,2),(2,2)])
two_dim

array([[2, 2],
       [2, 2]])

## 2. Reshape

In [42]:
A = np.arange(1, 13).reshape((3, 4))
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
AO = np.ones_like(A)
AO

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [44]:
AZ = np.zeros_like(A)
AZ

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [45]:
B = np.arange(1, 25).reshape(2, 3, 4)
print(B)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [46]:
toolong = np.arange(10000).reshape((100,100))
toolong

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

### Aratihmetic operations on arrays

In [47]:
a = np.array([2]*5)
b = np.array([3,3,3,3,3])

a+b

array([5, 5, 5, 5, 5])

In [48]:
a-b

array([-1, -1, -1, -1, -1])

In [49]:
a*b

array([6, 6, 6, 6, 6])

In [50]:
a%b

array([2, 2, 2, 2, 2])

### Logic operations on array

In [51]:
a > 2

array([False, False, False, False, False])

In [52]:
a >= 2

array([ True,  True,  True,  True,  True])

## 2D arrays

### Artihmetic

In [53]:
A = np.array([[1,1], [1,1]])
B = np.array([[2,2], [2,2]])

In [54]:
A + B

array([[3, 3],
       [3, 3]])

In [55]:
A - B

array([[-1, -1],
       [-1, -1]])

In [56]:
A * B

array([[2, 2],
       [2, 2]])

In [57]:
A / B

array([[0.5, 0.5],
       [0.5, 0.5]])

In [58]:
A % B

array([[1, 1],
       [1, 1]])

In [59]:
print(A)
A *= 2
print(A)

[[1 1]
 [1 1]]
[[2 2]
 [2 2]]


In [60]:
print(B)
B += 2
print(B)

[[2 2]
 [2 2]]
[[4 4]
 [4 4]]


### Logic

In [61]:
A > B

array([[False, False],
       [False, False]])

### Matrix multiplication

In [62]:
A.dot(B)

array([[16, 16],
       [16, 16]])

In [63]:
C = np.array([[1,2,3], [4,5,6]])
D = np.array([[2,2], [2,2], [2,2]])

In [64]:
C.dot(D)

array([[12, 12],
       [30, 30]])

In [65]:
np.dot(C, D)

array([[12, 12],
       [30, 30]])

### Accumulative

In [66]:
A = np.arange(1,12)
print(A.sum())
print(A.sum())

66
66


### Axis operations

In [76]:
d = np.arange(15).reshape((3, 5))
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [77]:
print(d.sum(axis=0))
print(d.sum(axis=1))

[15 18 21 24 27]
[10 35 60]


In [78]:
d.mean(axis=1)

array([ 2.,  7., 12.])