## 1.Basic Initialization

In [4]:
import numpy as np

In [7]:
angles = np.array([0, 30, 45, 60, 90])
print(angles)

[ 0 30 45 60 90]


In [10]:
rad = np.radians(angles)
print(rad)

[0.         0.52359878 0.78539816 1.04719755 1.57079633]


In [12]:
sines = np.sin(rad)
print(sines)

[0.         0.5        0.70710678 0.8660254  1.        ]


In [14]:
cosines = np.cos(rad)
print(cosines)

[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [16]:
print(np.degrees(np.arcsin(sines)))

[ 0. 30. 45. 60. 90.]


In [19]:
score = np.random.random(10)
score

array([0.24344463, 0.44509857, 0.14559155, 0.46803969, 0.75992038,
       0.3856833 , 0.18847521, 0.31335039, 0.5194083 , 0.45766686])

In [31]:
average =np.mean(score)
median = np.median(score)
variance = np.var(score)
standard_dev = np.std(score)

In [33]:
print(f'Average = ', average)
print(f'Median = ', median)
print(f'Variance = ', variance)
print(f'Standard deviation = ', standard_dev)

Average =  0.39266788646537343
Median =  0.41539093514640346
Variance =  0.029494127019332628
Standard deviation =  0.17173854261444235
