## 1.Slicing

In [4]:
import numpy as np

a = np.arange(21)
p2 = a**2
print(p2)

[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289
 324 361 400]


In [7]:
p2[2:-2:2]

array([  4,  16,  36,  64, 100, 144, 196, 256, 324])

In [13]:
p2[::-3]

array([400, 289, 196, 121,  64,  25,   4])

In [38]:
p2[-2:-5:-1]

array([361, 324, 289])

## 2. 2d Slicing

In [39]:
people = np.array([['john', 'ante', 'peter'], ['1', '2', '3'], ['w', 'rw', 'a']], dtype='<U7')
people[0, 1]

'ante'

In [40]:
people[0:2, 1:3]

array([['ante', 'peter'],
       ['2', '3']], dtype='<U7')

In [41]:
people[::-1, ::-1]

array([['a', 'rw', 'w'],
       ['3', '2', '1'],
       ['peter', 'ante', 'john']], dtype='<U7')

## 3. 3d Slicing

In [43]:
cube = np.array([

    [['john', 'ante', 'peter'], 
    ['1', '2', '3'], 
    ['w', 'rw', 'a']],
    [['22', '22', '22'], 
    ['33', '33', '33'], 
    ['11', '11', '11']]    
], dtype='<U7')

print(cube[::-1, ::-1, ::-1])

[[['11' '11' '11']
  ['33' '33' '33']
  ['22' '22' '22']]

 [['a' 'rw' 'w']
  ['3' '2' '1']
  ['peter' 'ante' 'john']]]
