## 1.Iterating

In [11]:
import numpy as np

A = np.array([['ante', 'john', 'peter'], [1,2,3], ['w', 'rw', 'r']])

for i in A:
    print(i)


print(A.flatten())
print(A.flatten(order='F'))

['ante' 'john' 'peter']
['1' '2' '3']
['w' 'rw' 'r']
['ante' 'john' 'peter' '1' '2' '3' 'w' 'rw' 'r']
['ante' '1' 'w' 'john' '2' 'rw' 'peter' '3' 'r']


In [18]:
import numpy as np

a = np.arange(12).reshape(3, 4)
print(a)
print(*np.nditer(a))
print(*np.nditer(a, order='F'))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0 1 2 3 4 5 6 7 8 9 10 11
0 4 8 1 5 9 2 6 10 3 7 11
