## 1.Reshaping

In [3]:
import numpy as np

a = np.arange(20).reshape(5, 4)
print(a)
print(a.ravel())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [11]:
import numpy as np

a = np.arange(24).reshape(3,8)
print(a)
# print(a.T)
# print(a.T.ravel())
a.shape

print(a.reshape(8,3))



[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [21]:
import numpy as np

countries = np.array(['germany', 'france', 'denmark', 'austria', 'spain', 'norway'])

print(countries.reshape(-1, 3))

print(countries.reshape(3, -1))

[['germany' 'france' 'denmark']
 ['austria' 'spain' 'norway']]
[['germany' 'france']
 ['denmark' 'austria']
 ['spain' 'norway']]
