## 1.Splitting

In [15]:
import numpy as np

A = np.arange(9)

print(np.split(A, 3))

print(np.split(A, [2,4, 6]))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7, 8])]


In [19]:
import numpy as np

B = np.arange(18).reshape(3,6)
print(B)
print(np.hsplit(B, 3))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]
