## 1.2x2 system

In [15]:
import numpy as np

A = np.array([[2,3],[2,4]])    

b = np.array([4,5])

print(np.linalg.solve(A, b))
print('Determinant of given matrix A is', np.linalg.det(A))

[0.5 1. ]
Determinant of given matrix A is 2.0


## 2.3x3 system

In [23]:
import numpy as np

A = np.array([[2,3, 2],[1, -2,4], [3,1,-3]], dtype=np.float64)   
b = np.array([4,5,7], dtype=np.float64)
solution = np.linalg.solve(A, b)
print(solution)
print('Determinant of given matrix A is', np.linalg.det(A))

[ 2.77777778 -0.66666667  0.22222222]
Determinant of given matrix A is 63.00000000000005


In [24]:
M = np.hstack((A, b.reshape(3, 1)))
print(M)

[[ 2.  3.  2.  4.]
 [ 1. -2.  4.  5.]
 [ 3.  1. -3.  7.]]


In [25]:
def multiply_row_by(M, row_number, mul_with):
    m_copy = M.copy()
    m_copy[row_number] *= mul_with
    return m_copy

print(multiply_row_by(M, 1, 2))

[[ 2.  3.  2.  4.]
 [ 2. -4.  8. 10.]
 [ 3.  1. -3.  7.]]


In [26]:
def add_rows_elimination(M, row_1, row_2, row_1_mul):
    mc = M.copy()
    mc[row_2] += mc[row_1] * row_1_mul
    return mc

print(M)
print(add_rows_elimination(M, 1, 2, -3))

[[ 2.  3.  2.  4.]
 [ 1. -2.  4.  5.]
 [ 3.  1. -3.  7.]]
[[  2.   3.   2.   4.]
 [  1.  -2.   4.   5.]
 [  0.   7. -15.  -8.]]


In [27]:
def  swap_rows(M, row_1, row_2):
    mc = M.copy()
    mc[[row_1, row_2]] = mc[[row_2, row_1]]
    return mc

print('Before swap')
print(M)
print('After swap')
print(swap_rows(M, 0, 2))

Before swap
[[ 2.  3.  2.  4.]
 [ 1. -2.  4.  5.]
 [ 3.  1. -3.  7.]]
After swap
[[ 3.  1. -3.  7.]
 [ 1. -2.  4.  5.]
 [ 2.  3.  2.  4.]]


In [43]:
A = add_rows_elimination(M, 0, 1, -1/2)
print(A)

[[ 2.   3.   2.   4. ]
 [ 0.  -3.5  3.   3. ]
 [ 3.   1.  -3.   7. ]]


In [44]:
A = add_rows_elimination(A, 0, 2, -3/2)
print(A)

[[ 2.   3.   2.   4. ]
 [ 0.  -3.5  3.   3. ]
 [ 0.  -3.5 -6.   1. ]]


In [45]:
A = add_rows_elimination(A, 1, 2, -1)
print(A)

[[ 2.   3.   2.   4. ]
 [ 0.  -3.5  3.   3. ]
 [ 0.   0.  -9.  -2. ]]


In [46]:
A = multiply_row_by(A, 2, -1/9)

In [47]:
print(A)

[[ 2.          3.          2.          4.        ]
 [ 0.         -3.5         3.          3.        ]
 [-0.         -0.          1.          0.22222222]]


In [51]:
x3 = 0.22222222
x2 = (A[1,3] - x3*A[1,2]) / A[1,1]
x1 = (A[0, 3] - A[0,1]* x2 - A[0,2] * x3) / A[0,0]

In [52]:
print(x1, x2, x3)

2.777777782857143 -0.6666666685714286 0.22222222
